project:
  type: website

website:
  favicon: assets/favicon.svg
  search: false
  navbar:
    logo: "/assets/logo.png"
    logo-alt: "University of Bristol"

format:
  html:
    theme: assets/styles.scss
    page-layout: full
