---
title: Upcoming courses
---

You will be able to book onto courses **four weeks in advance**, via online booking forms on this page.

We'll send updates to our [training alerts mailing list](mailing-list.qmd) when new booking forms are available.
Make sure you're signed up, if you'd like to get the announcements!

For more information or if you have any questions, please [contact us](contact.qmd).

::: {.schedule}
Course                                                                                                                     | Date                   | Time   | Location | Links 
---------------------------------------------------------------------------------------------------------------------------|------------------------|--------|----------|--------------------------------------------------
<small>Lunch & Learn</small><br>Pre-registration & registered reports                                                      | Tue 18 March 2025      | 12-1pm | Online   | [Video](lunch-and-learn.qmd#Pre-registration & registered reports){.btn .btn-sm .btn-light}
<small>Training course</small><br>**Introduction to Python (part 1)**                                                      | Wed 19 March 2025      | 1-4pm  | Online   | [Resources](/intro-python-1/){.btn .btn-sm .btn-light}
<small>Lunch & Learn</small><br>Introduction to Git & GitHub                                                               | Tue 25 March 2025      | 12-1pm | Online   | [Video](lunch-and-learn.qmd#Introduction to git and GitHub){.btn .btn-sm .btn-light}
<small>Training course</small><br>**Introduction to R (part 1)**                                                           | Wed 26 March 2025      | 1-4pm  | Online   | [Resources](/beginning-r/){.btn .btn-sm .btn-light}
<small>Lunch & Learn</small><br>Can others reproduce your results? Using `uv` in a Python data analysis project            | Tue 1 April 2025       | 12-1pm | Online   | [Video](lunch-and-learn.qmd#Can others reproduce your results? Using \'uv\' in a Python data analysis project){.btn .btn-sm .btn-light}
<small>Lunch & Learn</small><br>A&E (Ask & Eat) drop-in session                                                            | Tue 8 April 2025       | 12-1pm | Online   | 
<small>Training course</small><br>**Introduction to Python (part 2)**                                                      | Wed 9 April 2025       | 1-4pm  | Online   | [Resources](/intermediate-python/){.btn .btn-sm .btn-light}
<small>Lunch & Learn</small><br>A&E (Ask & Eat) drop-in session                                                            | Tue 15 April 2025      | 12-1pm | Online   | 
<small>Training course</small><br>**Introduction to R (part 2)**                                                           | Wed 16 April 2025      | 1-4pm  | Online   | [Resources](/intermediate-r/){.btn .btn-sm .btn-light}
<small>Lunch & Learn</small><br>Can others reproduce your (conda) results? Using `pixi` in a Python data analysis project  | Tue 29 April 2025      | 12-1pm | Online   | [Video](lunch-and-learn.qmd#Can others reproduce your conda results? Using \'pixi\' in a Python data analysis project){.btn .btn-sm .btn-light}
<small>Lunch & Learn</small><br>Classification with scikit-learn: Decision Trees and Random Forests                        | Tue 6 May 2025         | 12-1pm | Online   | [Video](lunch-and-learn.qmd#Classification with scikit-learn: Decision Trees and Random Forests){.btn .btn-sm .btn-light}
<small>Training course</small><br>**Introduction to Data Analysis in Python**                                              | Wed 14 May 2025        | 1-4pm  | Online   | [Closed](){.btn .btn-sm .btn-primary .disabled}
<small>Lunch & Learn</small><br>Reproducible Data Science Projects                                                         | Tue 20 May 2025        | 12-1pm | Online   | [Closed](){.btn .btn-sm .btn-primary .disabled}
<small>Training course</small><br>**Introduction to Data Analysis in R**                                                   | Wed 21 May 2025        | 1-4pm  | Online   | [Closed](){.btn .btn-sm .btn-primary .disabled}
<small>Lunch & Learn</small><br>Introduction to GreenDiSC                                                                | Tue 27 May 2025        | 12-1pm | Online   | [Cancelled](){.btn .btn-sm .btn-light .disabled}
<small>Lunch & Learn</small><br>Practical Pytest                                                                  | Tue 17 June 2025        | 12-1pm | Online   | [Closed](){.btn .btn-sm .btn-primary .disabled}
<small>Lunch & Learn</small><br> Intro to the Theory of Neural Networks                                                              | Tue 24 June 2025        | 12-1pm | Online   | [Register](https://events.teams.microsoft.com/event/c0230216-4f4a-474a-a121-c7d9707ba0fb@b2e47f30-cd7d-4a4e-a5da-b18cf1a4151b){.btn .btn-sm .btn-primary}
<small>Lunch & Learn</small><br>Intro to Natural Language Processing (NLP) in Python Strings, regular expressions and fuzzy matching                                                                  | Tue 1 July 2025        | 12-1pm | Online   | [Register](https://events.teams.microsoft.com/event/ea72ef2c-0b73-4299-abf8-8ac6a9be4cba@b2e47f30-cd7d-4a4e-a5da-b18cf1a4151b){.btn .btn-sm .btn-primary}
:::

:::: {.content-hidden}
<!-- 
This is a template course catalogue.
Duplicate this content outside the {.content-hidden} block, rather than change this template.
-->

::: {.schedule}
Course                                  | Date                        | Time   | Location | Links 
----------------------------------------|-----------------------------|--------|----------|--------------
Beginning Python                        | Wednesday 2  October  2024  | 1-4pm  | Online   | [Course Full](){.btn .btn-sm .disabled}
Intermediate Python                     | Wednesday 9  October  2024  | 1-4pm  | Online   | [Course Full](){.btn .btn-sm .disabled}
Intro to Data Analysis in Python        | Wednesday 16 October  2024  | 1-4pm  | Online   | [Course Full](){.btn .btn-sm .disabled}
Beginning R                             | Monday    21 October  2024  | 1-4pm  | Online   | [Course Full](){.btn .btn-sm .disabled}
Intermediate R                          | Wednesday 23 October  2024  | 1-4pm  | Online   | [Course Full](){.btn .btn-sm .disabled}
Intro to Data Analysis in R             | Friday    25 October  2024  | 1-4pm  | Online   | [Register](https://events.teams.microsoft.com/event/...){.btn .btn-sm .btn-primary}
Best Practices in Software Engineering  | Wednesday 30 October  2024  | 1-4pm  | Online   | [Register](https://events.teams.microsoft.com/event/...){.btn .btn-sm .btn-primary}
Applied Data Analysis in Python         | Wednesday 6  November 2024  | 1-4pm  | Online   | [Register](https://events.teams.microsoft.com/event/...){.btn .btn-sm .btn-primary}
Introducing Version Control with Git    | Wednesday 13 November 2024  | 1-4pm  | Online   | [Register](https://events.teams.microsoft.com/event/...){.btn .btn-sm .btn-primary}
Introducing Parallel Python             | Wednesday 20 November 2024  | 1-4pm  | Online   | [Register](https://events.teams.microsoft.com/event/...){.btn .btn-sm .btn-primary}
:::

::::