---
title: Advice for teachers
---

All of our workshops have enough detail such that they can be studied as self-guided workshops by individuals. When taught, they work best as three-hour workshops with a 5-10 minute break every hour. The best approach is to walk through the material via live-coding, and then giving time for students to complete the exercises that are at the bottom of most pages. The answers are linked. We recommend, if teaching online, that you have both a lead presenter, who talks through the material and live-codes, and a narrator, who types in chat to highlight key points, plus answer text-based questions from students, solve technical issues, or triage questions across to break-out rooms with helpers (if you have any). A lead and narrator together can run classes for about 50-70 students, assuming either that students have already installed any pre-requisite software (such as anaconda python) or you have some helpers around at the start who can help debug any technical issues. We have taught up to 120 students at a time, but recommend for this number that you will need at least 1-2 extra helpers who can work with small groups in break out rooms.

There is in general more material in each course that the average student will get through in the three hours as there is always a wide spread of abilities. Make sure to point out the material will remain online and encourage them to go through it in their own time after the session. We always encourage that students use their own computers / laptops to run the material so that they can more easily carry on afterwards. All of our workshops work well on Windows, MacOS or Linux.

We are in the process of recording videos of our most popular workshops and putting them on YouTube. This should help students refresh material, as well as enabling others to run these workshops using a "virtual trainer".

